version: "3.9"

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./front:/app
      - /app/node_modules
    command: npm run dev -- --host

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    command: npm run start
